name: CI/CD

on:
  push:
    branches: [main]
  
  workflow_dispatch:


jobs:
  # Job #1 -> Compilar y generar imagen Docker en Runner de Github
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: DockerfileProd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nest-rest-api:latest

  
  # Job #2 -> Desplegar el contenedor en el servidor privado. Se ejecuta en runner autohospedado: eela-ubuntu-runner
  deploy:

    needs: build

    runs-on: self-ubuntu

    steps: 
      - name: Deploy Docker container
        run: |
          docker stop nest-rest-api || true
          docker rm nest-rest-api || true
          docker run --pull always -d -p 82:3000 --name nest-rest-api \
          --env DB_HOST=${{ secrets.DB_HOST }} \
          --env DB_PORT=${{ secrets.DB_PORT }} \
          --env DB_USERNAME=${{ secrets.DB_USERNAME }} \
          --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --env DB_NAME=${{ secrets.DB_NAME }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/nest-rest-api:latest

